const choice = [{header: "Exceptional Quality", content: "We are committed to sourcing only the freshest flowers to ensure that every arrangement is a masterpiece of beauty."} , {header: "Beautiful Presentation" , content: "Our floral arrangements are expertly designed and elegantly presented, reflecting sophistication and attention to detail."} , {header: "Prompt delivery" , content: "Whether it's a last-minute gift or a scheduled event, our efficient team ensures fresh, on-time flower arrivals."} ];

const reviews = [
    {profile: "home/profile.png" , name: "Sarah Hemsworth" , review: "This flower shop is a gem! Their attention to detail is remarkable, and it truly shows in the quality of their arrangements. I've received multiple bouquets from them, and each time, I've been blown away by the beauty and freshness of the flowers. It's a pleasure supporting such a talented and passionate team."} , 
    {profile: "home/profile.png" , name: "Sarah Hemsworth" , review: "This flower shop is a gem! Their attention to detail is remarkable, and it truly shows in the quality of their arrangements. I've received multiple bouquets from them, and each time, I've been blown away by the beauty and freshness of the flowers. It's a pleasure supporting such a talented and passionate team."} , 
    {profile: "home/profile.png" , name: "Sarah Hemsworth" , review: "This flower shop is a gem! Their attention to detail is remarkable, and it truly shows in the quality of their arrangements. I've received multiple bouquets from them, and each time, I've been blown away by the beauty and freshness of the flowers. It's a pleasure supporting such a talented and passionate team."} , 
    {profile: "home/profile.png" , name: "Sarah Hemsworth" , review: "This flower shop is a gem! Their attention to detail is remarkable, and it truly shows in the quality of their arrangements. I've received multiple bouquets from them, and each time, I've been blown away by the beauty and freshness of the flowers. It's a pleasure supporting such a talented and passionate team."} , 
    {profile: "home/profile.png" , name: "Sarah Hemsworth" , review: "This flower shop is a gem! Their attention to detail is remarkable, and it truly shows in the quality of their arrangements. I've received multiple bouquets from them, and each time, I've been blown away by the beauty and freshness of the flowers. It's a pleasure supporting such a talented and passionate team."} 
]

export {choice , reviews};